server:
  address: 0.0.0.0
  port: 8081

portaria-server:
#  base-url: http://10.4.0.111:8080/api 
  base-url: http://10.4.0.111:8080/api/portaria
  internal-token: TROQUE_POR_UMA_CHAVE_FORTE_AQUI
  
spring:
  application:
    name: portaria-notifier-server

logging:
  level:
    br.com.upa.notifier: DEBUG
  